name: whiteboard_mobile
description: Realtime whiteboard mobile

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"



dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.0

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"
  
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

 